name: wf-test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Docker/**"
      - "Docker-compose/**"
env:
  DockerHub_UserName: ${{ secrets.DOCKERHUB_USERNAME }}
  DockerHub_Password: ${{ secrets.DOCKERHUB_TOKEN }}
  DockerHub_RepoName: spm-openjdk-bootcamp-m14
  DockerHub_TagName: github_m16-17
  Docker_ContainerTag: m16-17
  Application_Original_Port: 3456
  Application_Expose_Port: 8001

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    
      - name: Concatena variables para reutilizar las existentes y crear otras
        run: |
          echo "Docker_ContainerName=${{env.DockerHub_RepoName}}_${{env.Docker_ContainerTag}}" >> $GITHUB_ENV
      
      - name: Checkout codigo del repositorio
        uses: actions/checkout@v3

      - name: Construir imagen docker a partir de dockerfile
        run:
          docker build . -t ${{env.DockerHub_UserName}}/${{env.DockerHub_RepoName}}:${{env.DockerHub_TagName}}_51
          -f Docker/Dockerfile
          
      - name: Start the service and perform healthcheck
        run: |
          docker run -d --name ${{env.Docker_ContainerName}} -p ${{env.Application_Expose_Port}}:${{env.Application_Original_Port}} ${{env.DockerHub_UserName}}/${{env.DockerHub_RepoName}}:${{env.DockerHub_TagName}}_51     
          docker run --network container:${{env.Docker_ContainerName}} appropriate/curl --retry 10 --retry-connrefused http://localhost:3456/
