name: wf-test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Docker/**"
      - "Docker-compose/**"
env:
  DockerHub_UserName: ${{ secrets.DOCKERHUB_USERNAME }}
  DockerHub_Password: ${{ secrets.DOCKERHUB_TOKEN }}
  DockerHub_RepoName: spm-openjdk-bootcamp-m14
  DockerHub_TagName: github_m16-17
  Docker_ContainerTag: m16-17
  Application_Original_Port: 3456
  Application_Expose_Port: 8001

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d -f ../Docker-Compose/Dockercompose.yaml
      - name: Test
        run: docker run --network container:spm-openjdk-bootcamp-m14-docker_compose_m16_17 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8001/
