name: wf-bootcamp-m16-17
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Docker/**"
env:
  DockerHub_UserName: ${{ secrets.DOCKERHUB_USERNAME }}
  DockerHub_Password: ${{ secrets.DOCKERHUB_TOKEN }}
  DockerHub_RepoName: spm-openjdk-bootcamp-m14
  DockerHub_TagName: github-m16-17
  Docker_ContainerName: ${DockerHub_RepoName}-m16-m17
  Application_Original_Port: 3456
  Application_Expose_Port: 8001

jobs:
  bootcamp-m16-17-job:
    runs-on: ubuntu-latest
    steps:
      - name: use env var
        run: echo ${{Docker_ContainerName}}
        
      - name: Checkout codigo del repositorio
        uses: actions/checkout@v3

      - name: Login en dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{env.DockerHub_UserName}}
          password: ${{env.DockerHub_Password}}
