name: wf-bootcamp-m15
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/Jenkinsfile'
      - '**/README.md'

env:
  DockerHub_UserName: ${{ secrets.DOCKERHUB_USERNAME }}
  DockerHub_Password: ${{ secrets.DOCKERHUB_TOKEN }}
  DockerHub_RepoName: spm-openjdk-bootcamp-m14
  DockerHub_TagName: github
  Docker_ContainerName: $DockerHub_RepoName
  Application_Original_Port: 3456
  Application_Expose_Port: 8001

jobs:
  bootcamp-m15-job:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout codigo del repositorio
        uses: actions/checkout@v3
        
      - name: Contruir imagen docker a partir de dockerfile
        run:
          docker build -t ${{env.DockerHub_UserName}}/${{env.DockerHub_RepoName}}:${{env.DockerHub_TagName}}_${{ github.run_number }} .
          
      - name: Ejecutar contenedor con la imagen docker creada anteriormente
        run:
          docker run -d --name ${{env.Docker_ContainerName}} -p ${{env.Application_Expose_Port}}:${{env.Application_Original_Port}} ${{env.DockerHub_UserName}}/${{env.DockerHub_RepoName}}:${{env.DockerHub_TagName}}_${{ github.run_number }}

      - name: Login en dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{env.DockerHub_UserName}}
          password: ${{env.DockerHub_Password}}

      - name: Push en dockerhub con la imagen docker creada anteriormente
        run:
          docker push ${{env.DockerHub_UserName}}/${{env.DockerHub_RepoName}}:${{env.DockerHub_TagName}}_${{ github.run_number }}
